# Generated by Django 4.1.6 on 2023-02-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_rename_attendees_event_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_creators', to='levelupapi.gamer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='skill_level',
            field=models.CharField(max_length=50),
        ),
    ]
